# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shop_pb2 as shop__pb2


class DistributedBookstoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChain = channel.unary_unary(
                '/DistributedBookstore/CreateChain',
                request_serializer=shop__pb2.CreateChainRequest.SerializeToString,
                response_deserializer=shop__pb2.CreateChainResponse.FromString,
                )
        self.Link = channel.unary_unary(
                '/DistributedBookstore/Link',
                request_serializer=shop__pb2.LinkRequest.SerializeToString,
                response_deserializer=shop__pb2.LinkResponse.FromString,
                )
        self.ListChain = channel.unary_unary(
                '/DistributedBookstore/ListChain',
                request_serializer=shop__pb2.ListChainRequest.SerializeToString,
                response_deserializer=shop__pb2.ListChainResponse.FromString,
                )
        self.ListBooks = channel.unary_unary(
                '/DistributedBookstore/ListBooks',
                request_serializer=shop__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=shop__pb2.ListBooksResponse.FromString,
                )
        self.Read = channel.unary_unary(
                '/DistributedBookstore/Read',
                request_serializer=shop__pb2.ReadRequest.SerializeToString,
                response_deserializer=shop__pb2.ReadResponse.FromString,
                )
        self.Write = channel.unary_unary(
                '/DistributedBookstore/Write',
                request_serializer=shop__pb2.WriteRequest.SerializeToString,
                response_deserializer=shop__pb2.WriteResponse.FromString,
                )
        self.Clean = channel.unary_unary(
                '/DistributedBookstore/Clean',
                request_serializer=shop__pb2.CleanRequest.SerializeToString,
                response_deserializer=shop__pb2.CleanResponse.FromString,
                )


class DistributedBookstoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Link(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedBookstoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChain': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChain,
                    request_deserializer=shop__pb2.CreateChainRequest.FromString,
                    response_serializer=shop__pb2.CreateChainResponse.SerializeToString,
            ),
            'Link': grpc.unary_unary_rpc_method_handler(
                    servicer.Link,
                    request_deserializer=shop__pb2.LinkRequest.FromString,
                    response_serializer=shop__pb2.LinkResponse.SerializeToString,
            ),
            'ListChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChain,
                    request_deserializer=shop__pb2.ListChainRequest.FromString,
                    response_serializer=shop__pb2.ListChainResponse.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=shop__pb2.ListBooksRequest.FromString,
                    response_serializer=shop__pb2.ListBooksResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=shop__pb2.ReadRequest.FromString,
                    response_serializer=shop__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=shop__pb2.WriteRequest.FromString,
                    response_serializer=shop__pb2.WriteResponse.SerializeToString,
            ),
            'Clean': grpc.unary_unary_rpc_method_handler(
                    servicer.Clean,
                    request_deserializer=shop__pb2.CleanRequest.FromString,
                    response_serializer=shop__pb2.CleanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DistributedBookstore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DistributedBookstore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/CreateChain',
            shop__pb2.CreateChainRequest.SerializeToString,
            shop__pb2.CreateChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Link(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/Link',
            shop__pb2.LinkRequest.SerializeToString,
            shop__pb2.LinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/ListChain',
            shop__pb2.ListChainRequest.SerializeToString,
            shop__pb2.ListChainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/ListBooks',
            shop__pb2.ListBooksRequest.SerializeToString,
            shop__pb2.ListBooksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/Read',
            shop__pb2.ReadRequest.SerializeToString,
            shop__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/Write',
            shop__pb2.WriteRequest.SerializeToString,
            shop__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Clean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedBookstore/Clean',
            shop__pb2.CleanRequest.SerializeToString,
            shop__pb2.CleanResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
